language: node_js
node_js:
  - stable
  - 10
  - 8
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_deploy: 
  - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
deploy:
  skip_cleanup: true
  provider: script
  script: git checkout HEAD yarn.lock && yarn build:canary
  on:
    node: stable
    branch: master
services: mongodb
git:
    submodules: false